---
name: React
description: A JavaScript library for building user interfaces
url: https://facebook.github.io
baseurl: "/"
permalink: "/blog/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
relative_permalinks: true
paginate: 5
timezone: America/Los_Angeles
highlighter: pygments
defaults:
- scope:
    path: ''
    type: post
  values:
    layout: post
- scope:
    path: docs
    type: page
  values:
    layout: docs
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - footnotes
sass:
  style: :compressed
  sass_dir: _css
gems:
- jekyll-redirect-from
- algoliasearch-jekyll
react_version: 0.14.0-alpha

algolia:
  application_id: latency
  index_name: reactjs
  record_css_selector: p,li,tr,h1,h2,h3,h4,h5,h6
  settings:
    highlightPostTag: </em>
    highlightPreTag: <em>
    minWordSizefor1Typo: 3
    minWordSizefor2Typos: 7
    ignorePlurals: true
    attributesToIndex:
      - title
      - text
      - category,subcategory,display_title
    attributesToHighlight:
      - category
      - subcategory
      - display_title
      - text
    customRanking:
      - desc(localized)
      - desc(page_score)
      - desc(weight_tag_name)
      - asc(weight_order)
      - desc(posted_at)
    ranking:
      - typo
      - words
      - proximity
      - attribute
      - custom
    attributesToSnippet:
      - text:20
    attributesForFaceting:
      - locale
    replaceSynonymsInHighlight: false
    synonyms:
      -
        - v0
        - '0'
